module.exports = {
  action: require('./action'),
  color: require('./color'),
  command: require('./command'),
  convert: require('./convert'),
  defaults: require('./defaults'),
  empty: require('./empty'),
  emultiple: require('./emultiple'),
  env: require('./env'),
  erequired: require('./erequired'),
  error: require('./error'),
  eunknown: require('./eunknown'),
  events: require('./events'),
  exec: require('./exec'),
  help: require('./help'),
  logger: require('./logger'),
  merge: require('./merge'),
  multiple: require('./multiple'),
  parser: require('./parser'),
  rc: require('./rc'),
  run: require('./run'),
  unparsed: require('./unparsed'),
  version: require('./version')
}
