#!/usr/bin/env node

/**
 *  Example subcommand program for exec.
 *
 *  ./bin/exec init [...]
 */
var path = require('path');
require('ttycolor')().defaults();
var pkg = path.normalize(path.join(__dirname, '..', '..', 'package.json'));
var cli = require('../..')(pkg);
cli
  .usage('<package...>')
  .version()
  .help()
  .on('empty', function(help, version) {
    help.call(this);
  })
  .on('complete', function(req) {
    if(req.args.length) console.log(this.name() + ' %s', req.args.join(' '));
  })
  .parse();
