#!/usr/bin/env node

/**
 *  Example program to test executing subcommands.
 *
 *  ./bin/exec enoent
 *  ./bin/exec eperm
 *  ./bin/exec init
 *  ./bin/exec init pkg@0.0.1
 */
var path = require('path');
require('ttycolor')().defaults();
var pkg = path.normalize(path.join(__dirname, '..', '..', 'package.json'));
var cli = require('../..')(pkg);
cli
  .configure({command: {exec: true}})
  .version()
  .help()
  .command('init', 'execute exec-init')
  .command('enoent', 'missing executable')
  .command('eperm', 'insufficent permission')
  .on('empty',function(help, version) {
    help.call(this);
  })
  .parse();
