#!/usr/bin/env node

/**
 *  Example program to test custom help output.
 *
 *  This program adds some examples to the help output
 *  and sets the output stream to process.stderr.
 *
 *  ./bin/help/custom
 *  ./bin/help/custom --help
 *  ./bin/help/custom --help --no-color
 */
var path = require('path');
var pkg = path.normalize(
  path.join(__dirname, '..', '..', 'package.json'));
var cli = require('../..'), help = cli.help;
cli(pkg, 'help/custom', 'Test program for custom help')
  .use(cli.middleware.debug)
  .use(cli.middleware.color)
  .version()
  .help()
  .on('help', function(data, document) {
    data.sections = data.sections || {};
    data.sections.examples = [
      {
        name: './bin/help/custom',
        description: 'Show customized help'
      },
      {
        name: './bin/help/custom --no-color',
        description: 'Disable ansi colors'
      }
    ]
    document.write(data, process.stdout);
  })
  .on('complete',function(req) {
    help.call(this);
  })
  .parse();
