#!/usr/bin/env node

/**
 *  Example program to test vanilla output when the color
 *  middleware is in use.
 *
 *  ./bin/help/vanilla
 *  ./bin/help/vanilla --plain
 *  ./bin/help/vanilla --help
 */
var path = require('path');
var pkg = path.normalize(
  path.join(__dirname, '..', '..', 'package.json'));
var package = require(pkg);
package.bugs.email = '<bug-gnu-utils@gnu.org>';
var cli = require('../..'), help = cli.help;
var description = "GNU `foo' does nothing interesting except serve ";
description += "as an example for `help2man'.";
var sections = {};
sections.examples = [
  {
    name: 'foo',
    description: 'do nothing'
  },
  {
    name: 'foo --option',
    description: 'the same thing, giving `--option\''
  }
]
var stash = {};
cli(package, 'foo', description)
  .configure({stash: stash,
    help: {sections: sections, vanilla: ~process.argv.indexOf('--plain')}})
  .use(cli.middleware.color)
  .option('-a, --option', 'an option')
  .option('-b, --another-option[=VALUE]', 'another option')
  .help()
  .version()
  .on('complete', function(req) {
    help.call(this);
  })
  .parse();
