.TH "CONFIG-SUBCOMMAND-CONF" "1" "March 2014" "config-subcommand-conf 1.0" "User Commands"
.SH "NAME"
config-subcommand-conf
.SH "DESCRIPTION"
.PP
Command to operate on a configuration.
.SH "SYNOPSIS"

\fB config\-subcommand conf <command> <args>\fR
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List configuration items.
.IP "\[ci]" 4
\fBget\fR: Get a configuration item.
.IP "\[ci]" 4
\fBset\fR: Set a configuration item.
.EL
.SH "BUGS"
.PP
Report bugs to muji noop@xpm.io.
