#!/usr/bin/env node

/**
 *  Example subcommand action callback.
 *
 *  ./bin/action print
 *  ./bin/action print [...]
 *  ./bin/action [...] print
 */
var path = require('path');
require('ttycolor')().defaults();
var pkg = path.normalize(path.join(__dirname, '..', 'package.json'));
var cli = require('..')(pkg);
cli.version().help()
  .on('empty',function(help, version) {
    help.call(this);
  })
cli.command('print')
  .description('print command line arguments')
  .action(function(cmd, opts, raw) {
    console.log(this._name + ' %s %j', cmd._name, raw);
  });
cli.parse();
