#!/usr/bin/env node

/**
 *  Example of declaring an option that conflicts with a program
 *  property, in this case a property decorated by the logger middleware.
 *
 *  ./bin/conflict
 */
var path = require('path');
var pkg = path.normalize(
  path.join(__dirname, '..', 'package.json'));
var cli = require('..');
cli(pkg)
  .use(cli.middleware.color)
  .use(cli.middleware.logger)
  .version()
  .help()
  .option('-l, --log [file]', 'middleware property conflict')
  .parse();
