#!/usr/bin/env node

/**
 *  Example program to test default version output.
 *
 *  ./bin/version/defaults
 *  ./bin/version/defaults --help
 */
var path = require('path');
require('ttycolor')().defaults();
var pkg = path.normalize(path.join(__dirname, '..', '..', 'package.json'));
var cli = require('../..')(pkg, 'version/defaults');
cli
  .version()
  .help()
  .on('empty', function(help, version) {
    version.call(this);
  })
  .parse();
